name: Tests

on:
  push:
    branches:
      - main
      - dev
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04
          - ubuntu-22.04
          - macos-latest
          - macos-15
          - windows-latest
          - windows-2022
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v4

        - name: Build Harbor CLI latest
          uses: ./

  test-build-from-source:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04
          - ubuntu-22.04
          - macos-latest
          - macos-15
          - windows-latest
          - windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go Compiler
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.x'
          cache: true

      - name: Build Harbor CLI from source
        uses: ./
        with:
          build_from_source: 'true'

  test-failed-main-and-not-build-from-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Harbor CLI with version 'main' but build_from_source false
        id: test-fail-main
        continue-on-error: true
        uses: ./
        with:
          version: main
          build_from_source: 'false'

      - name: Assert action failed for main without build from source
        shell: bash
        run: |
          if [[ "${{ steps.test-fail-main.outcome }}" != "failure" ]]; then
            echo "ERROR: Expected action to fail, but outcome was '${{ steps.test-fail-main.outcome }}'"
            exit 1
          fi

          echo "Step failed as expected for main without build from source"

  test-failed-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Harbor CLI non existent version
        id: test-fail
        continue-on-error: true
        uses: ./
        with:
          version: 9999.0.0

      - name: Assert action failed
        shell: bash
        run: |
          if [[ "${{ steps.test-fail.outcome }}" != "failure" ]]; then
            echo "ERROR: Expected action to fail, but outcome was '${{ steps.test-fail.outcome }}'"
            exit 1
          fi

          echo "Step failed as expected"
