name: Tests

on:
  push:
    branches:
      - dev
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04
          - ubuntu-22.04
          - macos-latest
          - macos-15
          - windows-latest
          - windows-2022
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v4

        - name: Build Harbor CLI latest
          uses: ./

  test-build-from-source:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04
          - ubuntu-22.04
          - macos-latest
          - macos-15
          - windows-latest
          - windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Build Harbor CLI from source
        uses: ./
        with:
          build_from_source: 'true'
